config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'encounters#index'

  get 'worklist', to: 'encounters#index'

  get 'home', to: 'static_pages#home'  
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact' #WORKS
  #get 'providerdetail/:npi', to: 'providerdetail#npi'  
  get 'npi/:npi', to: 'static_pages#npi' #routes
  	#@npi = params[:npi] #controller
  get 'spotfire', to: 'static_pages#spotfire' #Spotfire Utilization notes

  #Nested Resource
  resources :encounters, only: [:index, :show] do 
  	resources :notes 	
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :encounter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  def index
    @encounters = Encounter.limit(10).all.sort_by { |e| e[:patient_age]}
  end
end

app/controllers/notes_controller.rb
require 'betterdoctor_helper'
require 'json'

class NotesController < ApplicationController
  
  include BetterdoctorHelper
  def index
  	p "Index Page"
    @encounter_id = params[:encounter_id]
    @encounter = Encounter.find(@encounter_id)
    @pan = Encounter.find(@encounter_id).patient_account_number
    @doctors = JSON.parse(BetterdoctorHelper.get_doctors(@encounter))
    @notes = Note.where("encounter_id = ?", params[:encounter_id])
  end

  def show
  	#link_to("Show Note page", encounter_note_path(@encounter_id, note))
  	@encounter_id = params[:encounter_id]
  	@note_id = params[:id]
  	@note = Note.find(params[:id])
  end

  def new
  	@encounter_id = params[:encounter_id]
  	#@encounter_patient_account_number = params[:patient_account_number]
  	@note = Note.new
  end

  def create  #required params NOT WORKING!!?
  	p "In the create method!!!!"
  	note = Note.new(note_params)
  	p note
  	note.encounter_id = params[:encounter_id]
  	p note.encounter_id
  	#NOT WORKING Pass PAN from Enc to Note
  	#note.patient_account_number = params[:patient_account_number]
  	#p note.patient_account_number #nil?? why?
  	note.save
  	redirect_to encounter_notes_path(params[:encounter_id])
  end

  def edit  #WORKING!!!
    @encounter_id = params[:encounter_id] 
    @note_id = params[:id] 
    @note = Note.find(params[:id]) 
  end 

  def update   #WORKING!!
    @encounter_id = params[:encounter_id] 
  #	@note_id = params[:id] 
    @note = Note.find(params[:id]) 
    @note.update_attributes(note_params) 
  	redirect_to encounter_notes_path 
  end 

  def destroy  	#WORKING!!
  	#<td><%= link_to 'Delete Note', encounter_note_path, method: :delete %></td>
  	@encounter_id = params[:encounter_id]
  	#@note_id = params[:id]
  	@note = Note.find(params[:id])
    @note.destroy
    redirect_to encounter_notes_path 
  end

  private

  def note_params
  	params.require(:note).permit(:content, :staff_initials)
  	#params.require(:note).permit(:patient_account_number, :content, :staff_initials)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def about
        #Ruby <%= link_to "About", static_pages_about_path %>
        #HTML <a href="/static_pages/about">About</a>
 		#static_pages_about_path #WORKS, removed based on youtube video
    end
    
    def contact
    	@email = "myemail@changehealthcare.com"
    end
	
	include BetterdoctorHelper
    def npi
    	@npi = params[:npi] #controller
    	#@doctors = JSON.parse(BetterdoctorHelper.get_doctors(@encounter)) #from notes_controller.rb
    	@providerdetails = JSON.parse(BetterdoctorHelper.get_providerdetails(@npi))
    end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/betterdoctor_helper.rb
require 'net/http'

module BetterdoctorHelper
 def self.get_doctors(encounter)
    #How do I pass 2 parameters / variables to the Request URL???
    latitude = encounter.latitude.to_s
    longitude = encounter.longitude.to_s

    #for Dev WORKING        
    #url2 = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors?location=az-phoenix&sort=best-match-desc&skip=0&limit=5&user_key=' + 'dca937486')   
    #url1 = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors?location=33.2765%2C%20-112.1872%2C%2010&sort=best-match-desc&skip=0&limit=5&user_key=' + 'dca93786')  
    #url = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors?location=' + latitude +'%2C%20' + longitude + '%2C%2010&sort=best-match-desc&skip=0&limit=5&user_key=' + 'dca9486') 
    #for Production WORKING
    url = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors?location=' + latitude +'%2C%20' + longitude + '%2C%2010&sort=best-match-desc&skip=0&limit=5&user_key=' + ENV['BD_API'])   

    req = Net::HTTP::Get.new(url.to_s)
    req['Accept'] = 'application/json'
    #req.add_field('Authorization', 'SHAREDKEY 1197:n1ndBzCNh+hW7kbVueswEsCGNiDd1yS6U4MKk3kOe14=')
    res = Net::HTTP.new(url.host, url.port)
    res.use_ssl = true
    res.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = res.request(req)
    response.body
  end

  def self.get_providerdetails(npi)
    #URL Working
    #https://api.betterdoctor.com/2016-03-01/doctors/npi/1710988381?user_key=dca937486

    #for Developement
    #url = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors/npi/' + npi + '?user_key=' + 'dca9e6') 

    #for Production WORKING
    url = URI.parse('https://api.betterdoctor.com/2016-03-01/doctors/npi/' + npi + '?user_key=' + ENV['BD_API'])   

    req = Net::HTTP::Get.new(url.to_s)
    req['Accept'] = 'application/json'
    #req.add_field('Authorization', 'SHAREDKEY 1197:n1ndBzCNh+hW7kbVueswEsCGNiDd1yS6U4MKk3kOe14=')
    res = Net::HTTP.new(url.host, url.port)
    res.use_ssl = true
    res.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = res.request(req)
    response.body
  end
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
	def get_betterdoctor_results
		# use HTTP client to issue call to BetterDoctor
		# store results in a variable and return variable
	end
end

app/views/encounters/index.html.erb
    <header class='clearfix'>
        <ul>
          <li><%= link_to image_tag("ch_delta_red_logo_sm.png"), "https://www.changehealthcare.com/" %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Worklist", worklist_path %></li>
          
        </ul>
    </header>

<body>
<div class='content'>
<h1>Patient Worklist</h1>

<table id="encounters">
	<tbody>
		<tr>
			<th>PAN</th>
			<th>Discharge Date</th>
			<th>Zip Code</th>
			<th>Latitude</th>
			<th>Longitude</th>
			<th>Age</th>
			<th>Total Cost</th>
			<th>Transition Notes</th>
		<% @encounters.each do |encounter| %>
		<tr>
			<td><%= encounter.patient_account_number %></td>
			<td><%= if encounter.discharge_date.nil? 
				"Missing?" 
				else encounter.discharge_date 
					end %></td>
			<td><%= encounter.zip_code %></td>
			<td><%= encounter.latitude %></td>
			<td><%= encounter.longitude %></td>
			<td><%= encounter.patient_age %></td>
			<td><%= (encounter.total_cost).round(2) %></td>
			<td bgcolor="#F42A4D">
				<%= link_to 'See Notes', encounter_notes_path(encounter) %></td>
		</tr>
		<% end %>

	</tbody>
</table>

<br>
<b>Disclaimer:</b> Fake Data
<br>
<%= link_to image_tag("CH_REV_red_logo-01-small.jpg"), "https://www.changehealthcare.com/" %>
<br>

<button class="collapsible">How to Query the Web App Database...</button>
<div class="bodycontent">
  <p></p>
  	<h3>Controller to View Ruby Code</h3>
  	<pre>  ..\app\controllers\encounters_controller.rb</pre>
	<pre>  @encounters = Encounter.limit(10).all.sort_by { |e| e[:patient_age]}</pre>

  	<h3>Total # of Encounters: <%= Encounter.count %> </h3>
  	<pre>  Encounter.count </pre>

	<h3>Avg Cost per Encounter: $
		<%= (Encounter.sum(:total_cost) / Encounter.count).round(0)  %> </h3>
	<pre>  (Encounter.sum(:total_cost) / Encounter.count).round(0) </pre>
	
	<h3>Potential ACO Savings: $
		<%= (Encounter.sum(:total_cost) / Encounter.count).round(0)*9  %> </h3>
	<pre>  (Encounter.sum(:total_cost) / Encounter.count).round(0)*9 </pre>
</div>

</div>
</body>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

app/views/notes/index.html.erb
    <header class='clearfix'>
        <ul>
          <li><%= link_to image_tag("ch_delta_red_logo_sm.png"), "https://www.changehealthcare.com/" %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Worklist", worklist_path %></li>
  		  
          <li><%= link_to "Create Note", new_encounter_note_path(@encounter_id) %></li>
        </ul>
    </header>

<div class='content'>
<h1>Encounter Notes for <%= @encounter.patient_account_number %></h1>

<table id="encounters">
	<tbody>
		<tr>			
			<th>Note Content</th>
			<th>Staff Initials</th>
			<th>Note ID</th>
			<th>Internal Patient ID</th>
			<th>Create Date</th>
			<th>Update Date</th>
			<th>Edit Note</th>
			<th>Delete Note</th>
		 <% @notes.each do |note| %>		 
		<tr>			
			<td><%= note.content %></td>
			<td><%= note.staff_initials %></td>
			<td><%= note.id %></td>
			<td><%= note.encounter_id %></td>
			<td><%= note.created_at %></td>
			<td><%= note.updated_at %></td>
			<td><%= link_to "Edit Note", 
				edit_encounter_note_path(@encounter_id, note)%></td>
			<td><%= link_to 'Delete Note', 
				encounter_note_path(@encounter_id, note), method: :delete %></td>
		</tr>
		<% end %>

	</tbody>
</table>

<br>
<b>Disclaimer:</b> Fake Data
<br>

<%= link_to("Create note", new_encounter_note_path(@encounter_id)) %>
<br>
<%= link_to 'Go Back to Patient Encounter List', encounters_path, method: :get %>
<br>
<br>
<br>
<h4>Top 5 Local Doctors</h4>
<table>
    <tbody>
        <thead>
            <th>NPI</th>
            <th>Name</th>
            <th>Title</th>
            <th>Picture</th>
        </thead>
	<% @doctors['data'].each do |data| %>
		<tr>
			<td><%= data['npi'] %></td>
	 		<td><%= data['profile']['last_name']%>, 
	 			<%= data['profile']['first_name']%></td>
	 		<td><%= data['profile']['title']%></td> 
	    	<td><img src=<%= data['profile']['image_url']%>></img></td>
		</tr>
	<% end %>
		</tbody>
</table>

<button class="collapsible">BetterDoctor API</button>
<div class="bodycontent">
  <p></p>
  API Documentation
<a href="https://developer.betterdoctor.com/documentation15">BetterDoctor Documentation</a>
<br>

Request URL Parameters for Doctor Search API Call
<UL>
	<LI><b>location</b> 
		<UL>
			<LI>Location slug = st-city
			<LI>Latitude, Longitude, Radius(miles) = <%= @encounter.latitude %>, <%= @encounter.longitude %>, 10
		</UL>
	<LI><b>sort</b> = best-match-desc
	<LI><b>skip</b> = 0
	<LI><b>limit</b> = 5
	<LI><b>user_key</b> = DCA234234352
</UL>

Request URL -> Response Body (JSON Parsed)
<br>
<br>
<b># of Doctors Found: </b>
<%= @doctors['meta']['total'] %> 
<br>
</div>

<button class="collapsible">Example Ruby Code to get JSON value(s):</button>
<div class="bodycontent">
 <p></p>
 <b>For Doctors</b>
<UL>
<LI>@doctors['data'][0]['profile']['last_name'] = 
<%= @doctors['data'][0]['profile']['last_name'] %>
<LI>
@doctors['data'][1]['profile']['last_name'] = 
<%= @doctors['data'][1]['profile']['last_name'] %>
</UL>

<b>For Practices</b>
<br>
<pre>  List all practices for 1st Provider: </pre>
<pre>  @doctors['data'][0]['practices'].each do |practice| </pre>
<UL>
<% @doctors['data'][0]['practices'].each do |practice| %> 
  <LI>
  practice['name'] = <%= practice['name'] %> 
<% end %> 

</div>


</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

app/views/static_pages/about.html.erb
    <header class='clearfix'>
        <ul>
          <li><%= link_to image_tag("ch_delta_red_logo_sm.png"), "https://www.changehealthcare.com/" %></li>
          <li><%= link_to "About", about_path %></li>

          <li><%= link_to "Worklist", root_path %></li>
          <li><%= link_to "Contact", contact_path%></li>
        </ul>
    </header>
<div class='content'>
<h2>Purpose</h2>
<iframe width="768" height="432" src="https://youtube.com/embed/gQnvbqP6SfY">
</iframe>
<br>
<a href="https://www.beckershospitalreview.com/healthcare-information-technology/try-this-to-reduce-readmissions-at-your-hospital.html">Case Study</a>
<br>
<a href="https://youtu.be/gQnvbqP6SfY">Webinar</a>
<br>
<h3>Potential Use Case: </h3>
Why are Transition Nurses critical in preventing 30 day readmissions? <br>
When are they successful and when are they not? <br>
My intent is to have an application that could log Transition Nurse activity and then figure out which set of actions are beneficial to certain patient populations.
<br>

</div>

app/views/static_pages/contact.html.erb
    <header class='clearfix'>
        <ul>
          <li><%= link_to image_tag("ch_delta_red_logo_sm.png"), "https://www.changehealthcare.com/" %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Worklist", worklist_path %></li>
          
        </ul>
    </header>

<div class='content'>

<h1>My Contact Info</h1>
<p><%= @email %></p>


<h1>Lessons Learned</h1>
<UL>
<LI>How to retrieve database values in Ruby</LI>
<UL>
	<LI>encounter.latitude</LI>
</UL>

<LI>How to parse & iterate JSON in Ruby</LI>
<UL>
	<LI>@doctors['data'][0]['profile']['last_name']</LI>
</UL>
<LI>How to pass values to from the Controller to the View</LI>
<LI>How to use nil? <%=nil.nil? %></LI>

</UL>


<h3>Learning Objectives</h3>
<ul>
	<li>Practice building a Web Application</li>
	<li>Learn about distributed version control</li>
	<li>Learn how to deploy code</li> 
	<li>Figure out hosting cost</li>
    <ul>
      <li>Heroku Free Hobby Dev</li>
      <li>550 free dyno hours per month (23 days)</li>
    </ul>
	<li>Learn how to leverage APIs</li>
	<li>Figure out API cost</li>
    <ul>
      <li>Tiers based on # of API calls</li>
      <li>Pay more for Premium features / content</li>
    </ul>
</ul>

<h3>Future Enhancements</h3>
<ul>
  <li>Update App Workflow</li>
  <li>Update Data Model</li>
  <li>Update Seed File</li>
  <li>Update UI / UX</li>
  	<ul>
  		<li>Add Navigation Bar</li>
  		<li>Add Carsousel</li>
  		<li>Add JavaScript Visualizations</li> 
  	</ul>
  <li>Add Machine Learning</li>
  	<ul>
  		<li>Calculate Risk Scores</li>
  		<li>Profile Providers & Patients</li>
  		<li>Estimate Cost Savings</li>
  	</ul>
  <li>Add APIs</li>
  	<ul>
  		<li>Learn how to leverage & use secrets.yml</li>
  		<li>BetterDoctor - Doctor Search by location</li>
  		<li>GoodRx - Fair Drug Price widget</li>
  		<li>Yelp - Provider Reviews</li>
  		<li>CMS Blue Button - Medicare Claims Data</li>
  		<li>PokitDoc - Out-of-Pocket Drug Price</li>
  		<li>First Data Bank - Drug Info</li>
  	</ul>
  <li>Security</li>
  	<ul>
  		<li>OAuth 2.0</li>
  	</ul>
</ul> 

<h3>git</h3>
<%=image_tag("iTerm2 git status 2018-10-16.png")%>


</div>

app/views/static_pages/home.html.erb
    <header class='clearfix'>
        <ul>
          <li><%= link_to image_tag("ch_delta_red_logo_sm.png"), "https://www.changehealthcare.com/" %></li>
          <li><%= link_to "About", about_path %></li>

          <li><%= link_to "Worklist", root_path %></li>
          <li><%= link_to "Contact", contact_path%></li>
        </ul>
    </header>

<div class='content'>
<h1>My Projects</h1>
<ul style="list-style-type:none;">
	<li><%= link_to "About", about_path %></li>
    <li><%= link_to "Patient Worklist", worklist_path %></li>
    <li><%= link_to 'NPI Provider Lookup', '/npi/1104919083' %></li>
    <li><%= link_to "Spotfire Utilization", spotfire_path %> (In Progress)</li>
    <li>DRG Game (Coming Soon)</li>
</ul>

<br>

<label class="textOverImage" style="background-image:url(https://web.opendrive.com/api/v1/download/file.json/NTlfNDgyMTkzNl8?inline=1)">
  <input type="checkbox">
  <h2>Grapes</h2>
  <div>
    Grapes can be eaten fresh as table grapes or they can be used for making wine, jam, juice, jelly, grape seed extract, raisins, vinegar, and grape seed oil
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://web.opendrive.com/api/v1/download/file.json/NTlfNDgyMDc3MV8?inline=1)">
  <input type="checkbox">
  <h2>Raspberry</h2>
  <div>
    The raspberry is the edible fruit of a multitude of plant species in the genus Rubus of the rose family, most of which are in the subgenus Idaeobatus; the name also applies to these plants themselves.
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://web.opendrive.com/api/v1/download/file.json/NTlfMTMzMTc3NjFf?inline=1)">
  <input type="checkbox">
  <h2>Text Area:<br> Controls</h2>
  <div>
    HTML table tag<br> 4 Property Controls (Input Field, Dropdown list)<br> 4 Action Controls (Button, Image)<br> Icon Images<br> Background Color
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://web.opendrive.com/api/v1/download/file.json/NTlfMTMzMTc2ODdf?inline=1)">
  <input type="checkbox">
  <h2>Bar Chart:<br> Daily Trend</h2>
  <div>
    Axes, Lines and Curves, Show/Hide Items
  </div>
</label>
<br>

<label class="textOverImage" style="background-image:url(https://lh3.googleusercontent.com/47xLW5uj-0w8M9KsN_fZ4oQ6ADmxuje2dy2DPt1QMBBnKeid2nDkRVkXhabv7QIGguuAv9gf1n9NAzjR0kEHjeaCoxPIWHsscsPxPDNP3bGtcNTOS51BfCY9fmNsfUmwbQrh4Wq0V9Q=w536-h357-no)">
  <input type="checkbox">
  <h2>Bar Chart</h2>
  <div>
    Description, Marking, Lines and Curves, Tooltip, Show and Hide
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://lh3.googleusercontent.com/qwiAhKfdE9ZciRXyLRk4aIpk8xsrlNO3UVm1kHw8H19Z-Ei24l4tQLH827_3fGLcKw84lvp4zgXOsbTazJLZIqhJFdF5ELRrN8MoRxVOMyfGhMh9VsLiJFPaam4A4kLgzOEEzXc2rBQ0OpD2Bh7XIcCMW-4CoV_Cvtu_2yvtNGKPxbUN4cPhRWb5KiY7oNc5Uh-WNZPi6MqpFxMuHvLTpLOcPgBC1y-_MYLQ4g4qeBD0VjaoUZO79_mLLYJL-iF8jPCloRSkCaCRwOqMJoii49TLoRPEfkS7N9RNsGFNSo_AcDj41ESrpAT1n8LbIywHp0uOZ6ts56KzPuUQzkYkTO-oIhstbNmmGpSliu29l7b1TY10_0U53R_kc4B1B6T48fNiwb0xMvXs93h_LemJIrhG3ilj6Ex2gYEXgsV-yDy9jNElWfLVlkGGWRml1U8J9ef-HzeDii9vwXAQNVMia3dkl10zxF0X176J5gyNyMkWT4U38FWiFfWqlZe3kCkGgVIERIROM2-kiBwY8-gTIrS4FEj12gH3NmoDdYs0-3-JdPHDQR6VTsF4hO_bG9IzLJHqOviZChTwVjMx27OqMsGIAiJvGcEO5H3Bj_I6PECF6Xgl1ezt5hNUWlL2_wtcuBtdCwkqFWimZB2fbQ8yviw9q2Y0n9fU=w537-h324-no)">
  <input type="checkbox">
  <h2>Bar Chart</h2>
  <div>
    Description, Marking, Custom Expression, Lines and Curves, Tooltip, Show and Hide
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://lh3.googleusercontent.com/vXzCGLZFF-lSS5p4WVXIt0Kt3oVKkWJTKbqlc_z5TLO3kaz8nNCzRqdRzDBQkMAsEsA1SzAqqDzbRmRSz2KwZe1CfgQ-eeWGnTvxxTAyogbC1Bkj8ygfK9bbkxLaRo2SorxHtGCiHWKI9c4R7DdiQhEaCY14jVmJwVqeCfqms7IK_OvNrZxKPCAcfiuH2sa8vU_vLp6mNOp8-ik3JyjTppEleaIvPPZMHKUB5YjrYiMWkEUlGQHip8tOGENwdugYtRza1nRi2oRa5IJhjkJioar9pYagP9jME46W_BEt-sDwDCLDh4szluxzku5IV5q0FSSWJMc6MoE9bv6_2c_VkU1MB-eaLBvvaL1Y-gDh0cpzPy80nEMIR9kcP32PFe4BTSmVRaW0Ty2BPJssehZ1X9njMIOxvr3jFkyIPqlU51iUGWDeqwmwTd2jR1RhOoNvrU0zcPp0Cqpx0BaYXzP1gK-X-pgsfZcgc2I1rJdwjDE-slIqhluDwzocqeeU-wlff1VdTBjG4P8XvWutdeiHnZhUtZ1XOT_jexZ4yQ0_2Aft2K_L1haZT8xnfakr3A3ypt6mWPpPjzUGpr5ZJb5WxE4rHI83NgZDr6DrcG1Ne_B_F3nYN_EqWENRWJd5VgLUQZjw6KwSFAahJzoHapfHTvXWX0vzqvAx=w241-h191-no)">
  <input type="checkbox">
  <h2>Text Area</h2>
  <div>
    HTML table tag<br> 4 Property Controls (Input Field, Dropdown list)<br> 4 Action Controls (Button, Image)<br> Icon Images<br> Background Color
  </div>
</label>
<label class="textOverImage" style="background-image:url(https://lh3.googleusercontent.com/iQ4ez9w-E4fIut__zYsia80LNylY0UGrYxRedhgq9L-k3ErbvvCHLYfjVL-hUThbAcC4VgfG8PvNGuw8K5ZVa6QQd_QUuMqPxplZNWvBms5eKbRRh49_r-CocoXQLQsMrVEiEBq_1FdrQul8Of9HGPgLQ9aVsB1BOz5JpeOcwRcbEOHRakAJo4Y2HR3aD9eYmmwj5gR3TbkKX_McZipW19iNJHAtmwO0l-94JS_rdIiiZNG7quvPDQ8zCTlMb5jFyqpLj2RHPlYs1MCn95FiLiB4lLIyDLBWqMzckYuxGtgiTibvl13r8ukAwtC38rVeeKMO6IDLQbt6hGFVpREK8NTBOBG7FU_Znswzbszp0dKEJbChl1ptIzdSGjiJ3izUPhWyo-xaArWLzMvS01VIxmwPKNojzNAvucZD6lnBs5ify5DP44iExdk0aoRiVQRhtoQJ-kiSIbTxS2aaPta3RcdGWS5ymA1CLTd4SqwFnucuwya0zU99c8bnFALm3DLJ-bD9zXK5873CBdZvgo7rJ5o5b78KsbaRLWWIt-jYWIKsX1HLszS3SK6pOIdTbWoIAbOjgqIw8GizeZpIW_lSelmgu05qXhdTUDzds8fVklinWfiktoGSLdJB9VcicSPwzXG6-iBaxunXyRrG7cDXjaX2bx9mJWG6=w702-h289-no)">
  <input type="checkbox">
  <h2>Colors</h2>
  <div>
    Color Palette, hex value, RGB, shades
  </div>
</label>
<br>
<br>
<%=image_tag("SpotfireUtilizationConsumer.png", :width => 100, :crop => "pad")%>
<br>
<br>

<button class="collapsible">Show Text Over An Image on Click Using Checkboxes</button>
<div class="bodycontent">
  <p></p>
  	<h3>Just need web images, HTML, CSS</h3>
  	<a href="https://codepen.io/zFunx/pen/QvzeBN">Sample Test HTML & CSS Code</a>
  	<pre>https://codepen.io/zFunx/pen/QvzeBN</pre>
  	<pre>Grapes https://web.opendrive.com/api/v1/download/file.json/NTlfNDgyMTkzNl8?inline=1</pre>
  	<pre>Raspberries https://web.opendrive.com/api/v1/download/file.json/NTlfNDgyMDc3MV8?inline=1</pre>
  	<pre>Bananas https://web.opendrive.com/api/v1/download/file.json/NTlfMTMzMTc3NjFf?inline=1</pre>
  	<pre>Oranges https://web.opendrive.com/api/v1/download/file.json/NTlfMTMzMTc2ODdf?inline=1</pre>
</div>

<button class="collapsible">JavaScript Carousel</button>
<div class="bodycontent">
  <p></p>
  	<h3>Want Picture Slide of Projects</h3>
  	<pre>???</pre>

</div>

<button class="collapsible">OCR Images</button>
<div class="bodycontent">
  <p></p>
  	<h3>Want to grab text from images</h3>
  	<pre>???</pre>

</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>


</div>